graphql:
  provider:
    security:
      jwt:
        enabled: true
        secret: LKX+BPFUvOSEuxktD4W7d5gLGl1KyRFsSWSSGwdSExA=
        accessTimeout: PT12H
        refreshTimeout: PT24H
      api:
        usernameArgName: email

# Special reminder!
#
# The accessTimeout and refreshTimeout are set to
# be very long for the convenience of experimentation
# and learning.
#
# Do not configure them in this way in real projects!
